name: Manual Deploy for Tests

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      godotVersion:
        description: 'Godot Version'
        required: true
        type: string
        default: '3.3.4'
      mono:
        description: 'Use mono version?'
        required: true
        default: false
        type: boolean
      runner:
        description: 'On what runner to use the action'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
        - macos-latest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gh-pages-deploy:
    runs-on: ${{ inputs.runner }}
      
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: vitorgus/setup-godot@dev
        with:
          godot-version: ${{ inputs.godotVersion }}
          mono: ${{ inputs.mono }}
      
      - name: Web Build - Linux
        if: ${{ inputs.runner == 'ubuntu-latest' }}
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" ./build/web/index.html
      
      - name: Web Build - Windows
        if: ${{ inputs.runner == 'windows-latest' }}
        run: |
          mkdir build/web
          Get-Command godot
          godot -v --export "HTML5" ./build/web/index.html
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build/web
