name: Custom Godot Build test

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  custom-godot-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        uses:  Vitorgus/Godot-Setup@dev
        with:
          godot-version: 3.3.3
